import type { Metadata } from 'next';
import { Geist, Geist_Mono, Jua } from 'next/font/google';
import './globals.css';
import { AppBar } from '@/components/AppBar';
import { AuthProvider } from './AuthProvider';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const jua = Jua({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-jua',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`
          min-h-screen
          bg-gradient-to-b from-[#fcbfc3] to-[#fff2f2]
          ${jua.variable}
        `}
      >
        <AuthProvider>
          <AppBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
